<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VesselPostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vesselCode = ["ARR/2020/114", "ARR/2020/115", "ARR/2020/116", "ARR/2020/117", "ARR/2020/118", "ARR/2020/129", "ARR/2020/130"];
        $dates = ["2025-07-19", "2025-07-20", "2025-07-21", "2025-07-22", "2025-07-23", "2025-07-24", "2025-07-25", "2025-07-25"];
        $times = [
            ['time' => '08:00:00', 'user_id' => 2],
            ['time' => '14:30:00', 'user_id' => 3],
        ];
        foreach ($vesselCode as $code) {
            foreach ($dates as $date) {
                foreach ($times as $entry) {
                    \App\Models\VesselPost::create([
                        'vp_user_id' => $entry['user_id'],
                        'vp_vsl_code' => $code,
                        'vp_pk_id' => 1,
                        'vp_post_date' => $date,
                        'vp_post_time' => $entry['time'],
                        'vp_latitude' => -6.200000,
                        'vp_longitude' => 106.816666,
                        'vp_shift' => 1,
                        'vp_note' => 'Generated by seeder',
                        'created_at' => $date . " " . $entry['time'],
                        'updated_at' => $date . " " . $entry['time'],
                    ]);
                }
            }
        }
    }
}
