<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use App\Models\VesselPost;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class VesselPostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        // 1. Hapus semua media dari database
        Media::truncate();

        // 2. Hapus folder media fisik
        Storage::deleteDirectory('public/media');

        $vesselCode = ["ARR/2020/114", "ARR/2020/115", "ARR/2020/116", "ARR/2020/117", "ARR/2020/118", "ARR/2020/129", "ARR/2020/130"];
        $dates = ["2025-07-19", "2025-07-20", "2025-07-21", "2025-07-22", "2025-07-23", "2025-07-24", "2025-07-25", "2025-07-25"];
        $times = [
            ['time' => '08:00:00', 'user_id' => 2],
            ['time' => '14:30:00', 'user_id' => 3],
        ];
        foreach ($vesselCode as $code) {
            foreach ($dates as $date) {
                foreach ($times as $entry) {
                    $vesselPost = \App\Models\VesselPost::create([
                        'vp_user_id' => $entry['user_id'],
                        'vp_vsl_code' => $code,
                        'vp_pk_id' => 1,
                        'vp_post_date' => $date,
                        'vp_post_time' => $entry['time'],
                        'vp_latitude' => -6.200000,
                        'vp_longitude' => 106.816666,
                        'vp_shift' => 1,
                        'vp_note' => 'Generated by seeder',
                        'created_at' => $date . " " . $entry['time'],
                        'updated_at' => $date . " " . $entry['time'],
                    ]);

                    $photoVesselPath = base_path('database/seeders/sample_file/vessel.jpg');
                    $photoSelfiePath = base_path('database/seeders/sample_file/selfie.jpg');

                    if (File::exists($photoVesselPath)) {
                        $vesselPost->addMedia($photoVesselPath)
                            ->preservingOriginal()
                            ->usingName('Photo Vessel')
                            ->withCustomProperties(['uploaded_by' => $entry['user_id']])
                            ->toMediaCollection('photo_vessel');
                    }

                    if (File::exists($photoSelfiePath)) {
                        $vesselPost->addMedia($photoSelfiePath)
                            ->preservingOriginal()
                            ->usingName('Photo Selfie')
                            ->withCustomProperties(['uploaded_by' => $entry['user_id']])
                            ->toMediaCollection('photo_selfie');
                    }
                }
            }
        }
    }
}
