name: Cacoon Deployment
description: Deploy Cacoon application to production server using SSH and Rsync.

on:
  workflow_dispatch:
    branches:
      - main
jobs:
  laravel-ssh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: akbaridc/cacoon
      - run: |
          git fetch --prune --unshallow --tags
          echo exit code $?
          git tag --list
          git describe --tags --always > version
          cp env/.env-dev.copy .env

      - uses: MilesChou/composer-action/8.2@master
        with:
          args: install --ignore-platform-reqs

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      # - run: |
      #     npm install
      #     npm run build

      - name: Deploy via rsync (manual)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.REMOTE_HOST_PORT }} ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          rsync $ARGS -e "ssh -p ${{ secrets.REMOTE_HOST_PORT }} -i ~/.ssh/id_rsa" ./ ${{ secrets.USERNAME }}@${{ secrets.REMOTE_HOST }}:${{ secrets.TARGET_DIRECTORY }}
        env:
          ARGS: "--ignore-times --compress --verbose --exclude=.git --exclude=.github --exclude=node_modules --no-perms --no-owner --no-group --recursive"
      - name: run ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_HOST_PORT }}
          script: |
            cd ${{ secrets.TARGET_DIRECTORY }}
            npm install
            npm run build
            php8.2 artisan key:generate --ansi
            php8.2 artisan view:cache
            php8.2 artisan cache:clear
