name: Cacoon Deployment
description: Deploy Cacoon application to production server using SSH and Rsync.

on:
  push:
    branches:
      - main
jobs:
  laravel-ssh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: akbaridc/cacoon
      - run: |
          git fetch --prune --unshallow --tags
          echo exit code $?
          git tag --list
          git describe --tags --always > version
          cp env/.env-dev.copy .env

      - uses: MilesChou/composer-action/8.2@master
        with:
          args: install --ignore-platform-reqs

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm install
          npm run build

      - name: Laravel Rsync Deploy
        uses: SHSharkar/Laravel-Rsync-Deploy@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "--ignore-times --compress --verbose --exclude=.git --exclude=.github --exclude=node_modules --no-perms --no-owner --no-group --recursive"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_HOST_PORT: ${{ secrets.REMOTE_HOST_PORT }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET_DIRECTORY: ${{ secrets.TARGET_DIRECTORY }}
      - name: run ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_HOST_PORT }}
          script: |
            cd ${{ secrets.TARGET_DIRECTORY }}
            ls database/migrations/
            php8.2 artisan key:generate --ansi
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan optimize:clear
